before_script:
  - ci/before_script.sh
  
stages:
  - build
  - test

cargo_build:
  stage: build
  script:
    - . environment
    - cargo build
  only:
    - master

cargo_test:
  stage: test
  script:
    - . environment
    - cargo test
  only:
    - master

variables:
  http_proxy: "http://127.0.0.1:3128/"
  https_proxy: "http://127.0.0.1:3128/"
